# -*- coding: utf-8 -*-
"""AdultExa1.5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-ewXlfnjdU6-xnppelx5rJ4XbtDuW2_V

Adult  
  
  Descripción:

Objetivo: Predecir si el ingreso de una persona es >50K o ≤50K al año (clasificación binaria).  

Archivo recomendado: adult.data y adult.test
Variables clave:  

| Variable | Tipo | Descripción |
|----------|------|------------|
| age | numérico | Edad del individuo |
| workclass | categórico | Tipo de trabajo |
| education | categórico | Nivel educativo |
| marital-status | categórico | Estado civil |
| occupation | categórico | Ocupación |
| race | categórico | Raza |
| sex | categórico | Sexo |
| hours-per-week | numérico | Horas trabajadas por semana |
| income | categórico | Objetivo: <=50K, >50K |
Filas y columnas: 32,561 filas en training, 15 columnas
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
sns.set(style="whitegrid")

# Rutas de los archivos

ruta_train = "/content/drive/MyDrive/adult.data"   # adultData
ruta_test = "/content/drive/MyDrive/adult.test"    # adultTest

# Adult Train

adultData = pd.read_csv(ruta_train, header=None, sep=',\s*', engine='python', na_values=' ?')

# Asignar columnas
adultData.columns = ["age","workclass","fnlwgt","education","education-num","marital-status",
                     "occupation","relationship","race","sex","capital-gain","capital-loss",
                     "hours-per-week","native-country","income"]

# Eliminar filas nulas
adultData = adultData.dropna()

# Adult Test

adultTest = pd.read_csv(ruta_test, header=None, sep=',\s*', engine='python', skiprows=1, na_values=' ?')

# Asignar columnas
adultTest.columns = ["age","workclass","fnlwgt","education","education-num","marital-status",
                     "occupation","relationship","race","sex","capital-gain","capital-loss",
                     "hours-per-week","native-country","income"]

# Eliminar filas nulas
adultTest = adultTest.dropna()

# Primer vistazo

print("Train dataset:")
display(adultData.head())
print("Test dataset:")
display(adultTest.head())