# -*- coding: utf-8 -*-
"""AmesHExa1.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oeoqsyrl2QLRM34ax0WIQ232SDuNi7ns

Ames Housing

Contenido clave:
| Variable | Tipo | Descripción |
|----------|------|------------|
| SalePrice | numérico | Precio de venta de la casa (objetivo principal) |
| LotArea | numérico | Tamaño del lote en pies cuadrados |
| OverallQual | categórico/numérico | Calidad general de la casa |
| YearBuilt | numérico | Año de construcción |
| Neighborhood | categórico | Barrio de la casa |
| GrLivArea | numérico | Área habitable arriba del suelo |  

Total de columnas: 81  

Total de filas: 2930
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="whitegrid")

# Cargar archivo Excel correctamente
ames = pd.read_excel("/content/drive/MyDrive/AmesHousingExa1.1.xls")

# Primer vistazo
print("Primeras filas de Ames Housing:")
display(ames.head())

# Información general
ames.info()

# Estadísticas descriptivas
ames.describe()

# Revisar valores nulos
print("Valores nulos por columna:")
print(ames.isnull().sum().sort_values(ascending=False).head(10))

# Limpieza mínima: rellenar numeric NA con 0
numeric_cols = ames.select_dtypes(include=['int64','float64']).columns
ames[numeric_cols] = ames[numeric_cols].fillna(0)

# Ejemplo gráfico: distribución del precio de venta
plt.figure(figsize=(8,5))
sns.histplot(ames['SalePrice'], bins=50, kde=True)
plt.title("Distribución de SalePrice")
plt.xlabel("SalePrice")
plt.show()