# -*- coding: utf-8 -*-
"""Aprendizaje no supervisado semi-supervisado activo 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CWO5QQss7CnepUWtYJJeZge3hcrKOBZA

Large Shoe Dataset (UT Zappos50k)  
es un conjunto de datos de imágenes de calzado recopilado originalmente por la Universidad de Texas en colaboración con la empresa Zappos. Contiene aproximadamente 50,000 imágenes de zapatos de distintos tipos, marcas y estilos.

Aprendizaje no supervizado

Importamos Librerias
"""

import os
import numpy as np
import cv2
import matplotlib.pyplot as plt

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

"""Ruta del dataset"""

DATASET_PATH = "/content/drive/MyDrive/ut-zap50k-images-square"

from google.colab import drive
drive.mount('/content/drive')

"""Cargar Imagenes"""

def cargar_imagenes(path, size=(64,64), max_images=8000):
    X = []

    for root, dirs, files in os.walk(path):
        for file in files:
            if len(X) >= max_images:
                break

            img_path = os.path.join(root, file)

            img = cv2.imread(img_path)
            if img is None:
                continue

            img = cv2.resize(img, size)
            img = img.flatten() / 255.0

            X.append(img)

    return np.array(X)

X = cargar_imagenes(DATASET_PATH)
print("Dataset shape:", X.shape)

max_images=3000

"""Aplicar K-means"""

k = 10  # probar otros valores

kmeans = KMeans(n_clusters=k, random_state=42)
labels = kmeans.fit_predict(X)

"""Clusters de las imagenes"""

def mostrar_cluster(X, labels, cluster_id, n=10):
    imgs = X[labels == cluster_id][:n]

    plt.figure(figsize=(12,2))
    for i, img in enumerate(imgs):
        plt.subplot(1, n, i+1)
        plt.imshow(img.reshape(64,64,3))
        plt.axis("off")
    plt.show()

# ejemplo
mostrar_cluster(X, labels, 0)

"""Imagenes Representativas"""

distancias = kmeans.transform(X)
idxs = np.argmin(distancias, axis=0)

representativas = X[idxs]

"""Representativas mas importantes"""

plt.figure(figsize=(12,4))

for i, img in enumerate(representativas):
    plt.subplot(2, 5, i+1)
    plt.imshow(img.reshape(64,64,3))
    plt.title(f"Cluster {i}")
    plt.axis("off")

plt.show()

"""Metodo del codo"""

inertia = []
ks = range(1, 15)

for k in ks:
    model = KMeans(n_clusters=k, random_state=42)
    model.fit(X)
    inertia.append(model.inertia_)

plt.plot(ks, inertia, "bo-")
plt.xlabel("k")
plt.ylabel("Inercia")
plt.title("Método del Codo")
plt.grid()
plt.show()

"""Silhouette score"""

scores = []

for k in range(2, 15):
    model = KMeans(n_clusters=k, random_state=42)
    labels_temp = model.fit_predict(X)
    score = silhouette_score(X, labels_temp)
    scores.append(score)

plt.plot(range(2,15), scores, "go-")
plt.title("Silhouette Score")
plt.xlabel("k")
plt.ylabel("score")
plt.grid()
plt.show()

"""Aprendizaje semi-supervisado

Calcular la distancia entre imagenes
"""

X_dist = kmeans.transform(X)

print("Shape distancias:", X_dist.shape)

"""Busca la imagen más cercana a cada cluster centroide"""

idxs = np.argmin(X_dist, axis=0)

X_representativas = X[idxs]

print("Representativas:", X_representativas.shape)

idxs = np.argmin(X_dist, axis=0) #selecciona

import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))

for i, img in enumerate(X_representativas):
    plt.subplot(2, int(len(X_representativas)/2), i+1)
    plt.imshow(img.reshape(64,64,3))
    plt.title(f"Cluster {i}")
    plt.axis("off")

plt.show()

y_representativas = np.random.randint(0, 5, size=len(X_representativas))

y_representativas = np.array([0, 1, 2, 1, 0, 3, 2, 4, 1, 0])

# Simulación de etiquetado manual
y_representativas = np.random.randint(0, 5, size=len(X_representativas))

from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(X_representativas, y_representativas)

y_propagado = np.empty(len(X))

for i in range(kmeans.n_clusters):
    y_propagado[kmeans.labels_ == i] = y_representativas[i]

y_propagado = np.empty(len(X))

for i in range(kmeans.n_clusters):
    y_propagado[kmeans.labels_ == i] = y_representativas[i]

log_reg2 = LogisticRegression(max_iter=1000) #mejor rendimiento

log_reg2.fit(X[:2000], y_propagado[:2000])

log_reg_random = LogisticRegression(max_iter=1000) #peor rendimiento

log_reg_random.fit(X[:len(X_representativas)], y_propagado[:len(X_representativas)])

y_filtrado = np.full(len(X), -1) #solo los más cercanos al centroide, reciben etiqueta

for i in range(kmeans.n_clusters):
    cluster_mask = (kmeans.labels_ == i)
    distancias_cluster = X_dist[:, i]

    umbral = np.percentile(distancias_cluster[cluster_mask], 30)

    mask_final = cluster_mask & (distancias_cluster <= umbral)
    y_filtrado[mask_final] = y_representativas[i]

"""Aprendizaje Activo

Probabilidad del modelo
"""

probas = log_reg2.predict_proba(X[:2000])

"""Nivel de confianza"""

labels_ixs = np.argmax(probas, axis=1)

confianza = np.array([
    proba[ix] for proba, ix in zip(probas, labels_ixs)
])

sorted_ixs = np.argsort(confianza) #armar por incertidumbre

"""Seleccionar muestras"""

k = 20  # número de muestras a revisar

X_dificiles = X[:2000][sorted_ixs[:k]]

"""Visualizar"""

plt.figure(figsize=(10,4))

for i, img in enumerate(X_dificiles):
    plt.subplot(2, 10, i+1)
    plt.imshow(img.reshape(64,64,3))
    plt.axis("off")

plt.show()

# Simulación etiquetado
y_dificiles = np.random.randint(0, 5, size=k)

"""Actualizar etiquetas"""

y_train2 = y_propagado[:2000].copy()

y_train2[sorted_ixs[:k]] = y_dificiles

"""Reentrenar modelo"""

from sklearn.linear_model import LogisticRegression

log_reg_activo = LogisticRegression(max_iter=1000)

log_reg_activo.fit(X[:2000], y_train2)