# -*- coding: utf-8 -*-
"""BikiExa1.4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SFr0uQfbsbuQZAgDPksEbY36RofoIEYe

Bike Sharing Demand
  Descripción:

Objetivo:  
 Predecir la demanda de bicicletas según condiciones climáticas y temporales.
Archivo recomendado:  

train.csv o day.csv (dependiendo de la versión que tengas)
Variables clave:  

| Variable | Tipo | Descripción |
|----------|------|------------|
| dteday | fecha | Fecha del registro |
| season | categórico | Temporada (1=primavera, 2=verano, 3=otoño, 4=invierno) |
| holiday | categórico | 0=no, 1=feriado |
| workingday | categórico | 0=no, 1=día laboral |
| temp | numérico | Temperatura normalizada |
| hum | numérico | Humedad normalizada |
| windspeed | numérico | Velocidad del viento normalizada |
| cnt | numérico | Total de bicicletas alquiladas (objetivo) |
Filas y columnas: depende de la versión, ~730 filas para daily data (day.csv)
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
sns.set(style="whitegrid")

# Ruta del archivo en tu Drive

ruta_bike = "/content/drive/MyDrive/sampleSubmissionExa1.4.csv"

# Cargar dataset

# Algunos archivos usan separador ',' pero pueden venir con espacios o codificación diferente
try:
    bike = pd.read_csv(ruta_bike, sep=',', encoding='utf-8')
except UnicodeDecodeError:
    bike = pd.read_csv(ruta_bike, sep=',', encoding='latin1')
except pd.errors.ParserError:
    # Si hay error de columnas, usar engine='python' con regex
    bike = pd.read_csv(ruta_bike, sep=',\s*', engine='python', encoding='latin1')

# Primer vistazo

print("Primeras filas:")
display(bike.head())

print("\nInformación general:")
bike.info()

print("\nEstadísticas descriptivas:")
display(bike.describe())

# Revisar valores nulos

print("\nValores nulos por columna:")
print(bike.isnull().sum())

# Limpieza mínima (si hay nulos)

for col in bike.columns:
    if bike[col].dtype == 'object':
        bike[col] = bike[col].fillna(bike[col].mode()[0])
    else:
        bike[col] = bike[col].fillna(bike[col].mean())

# Ejemplo gráfico: demanda por temporada (si existe columna 'season' o 'cnt')

if 'season' in bike.columns and 'cnt' in bike.columns:
    plt.figure(figsize=(8,5))
    sns.boxplot(x='season', y='cnt', data=bike)
    plt.title("Demanda de bicicletas por temporada")
    plt.show()
else:
    print("Columnas 'season' o 'cnt' no encontradas. Revisa el dataset.")