# -*- coding: utf-8 -*-
"""BreastCancerExa1.8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HKAIk6s4lKLafZljBJKVQllOZZAgPVii

Breast Cancer Wisconsin (Original)  

Descripción:

Objetivo: Clasificar tumores como malignos (M) o benignos (B) a partir de características de la célula.
Archivo  
  
 recomendado: breast-cancer-wisconsin.data
Variables clave:  

| Variable | Tipo | Descripción |
|----------|------|------------|
| ID | numérico | Identificador |
| Clump Thickness | numérico | Grosor del agrupamiento celular |
| Uniformity of Cell Size | numérico | Uniformidad del tamaño de la célula |
| Uniformity of Cell Shape | numérico | Uniformidad de la forma |
| Marginal Adhesion | numérico | Adhesión marginal |
| Single Epithelial Cell Size | numérico | Tamaño de célula epitelial simple |
| Bare Nuclei | numérico | Núcleos desnudos (puede tener missing values ?) |
| Bland Chromatin | numérico | Cromatina blanda |
| Normal Nucleoli | numérico | Núcleolos normales |
| Mitoses | numérico | Número de mitosis |
| Class | categórico | Objetivo: 2=benigno, 4=maligno |  

Filas y columnas: 699 filas, 11 columnas  

Uso típico: clasificación binaria, análisis médico
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
sns.set(style="whitegrid")

# Cargar dataset
bcw = pd.read_csv("/content/drive/MyDrive/breast-cancer-wisconsin.data", header=None, na_values='?')

# Asignar nombres
bcw.columns = ["ID","Clump Thickness","Cell Size","Cell Shape","Marginal Adhesion",
               "Single Epithelial Cell Size","Bare Nuclei","Bland Chromatin","Normal Nucleoli",
               "Mitoses","Class"]

# Primer vistazo
display(bcw.head())
bcw.info()
bcw.describe()

# Revisar valores nulos
print("Valores nulos:")
print(bcw.isnull().sum())

# Revisar valores nulos
print("Valores nulos:")
print(bcw.isnull().sum())

# Limpieza mínima: rellenar numericos con media
bcw = bcw.fillna(bcw.mean())

# Ejemplo gráfico: distribución de clases
sns.countplot(x='Class', data=bcw)
plt.title("Distribución de clases - Breast Cancer Wisconsin")
plt.show()