# -*- coding: utf-8 -*-
"""CenterPExa1.3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/118roemiQ6DijvsGJSyriG72wkF2SWXQK

Centers for Disease Control and Prevention  
2021-2023 Demographic Variables and Sample Weights DEMO_L Doc DEMO_L Data [XPT - 2.5 MB] September 2024  
  
  Archivo principal:
DEMO_L.XPT
Contenido clave:  

| Variable | Tipo | Descripción |
|----------|------|------------|
| SEQN | numérico | ID del participante |
| RIDAGEYR | numérico | Edad en años |
| RIAGENDR | categórico | Sexo (1=Hombre, 2=Mujer) |
| RIDRETH3 | categórico | Raza/Hispanic origin |
| WTMEC2YR | numérico | Peso de la muestra para análisis |
| SDMVPSU / SDMVSTRA | numérico | Variables de diseño muestral |
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="whitegrid")

# Cargar archivo XPT
nhanes = pd.read_sas("/content/drive/MyDrive/DEMO_L.xpt")

# Primer vistazo
print("Primeras filas NHANES:")
display(nhanes.head())

# Información general
nhanes.info()

# Estadísticas descriptivas
nhanes.describe()

# Revisar valores nulos
print("Valores nulos en NHANES:")
print(nhanes.isnull().sum().sort_values(ascending=False).head(10))

# Limpieza mínima: codificación de género
nhanes['RIAGENDR'] = nhanes['RIAGENDR'].replace({1:'Male', 2:'Female'})

# Ejemplo: distribución de edad por género
plt.figure(figsize=(8,5))
sns.histplot(data=nhanes, x='RIDAGEYR', hue='RIAGENDR', multiple='stack', bins=30)
plt.title("Distribución de Edad por Género - NHANES")
plt.xlabel("Edad")
plt.show()