# -*- coding: utf-8 -*-
"""ciberataque.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HO9RkP4aMOVR4D0nwbaoRngj4kBneE41

Conjunto de datos de ataques a redes de Kitsune  
Esta es una colección de nueve conjuntos de datos de ataques de red, capturados desde un sistema de vigilancia comercial basado en IP o una red con numerosos dispositivos IoT. Cada conjunto de datos contiene millones de paquetes de red y diferentes ciberataques.

Importar librerias
"""

# Commented out IPython magic to ensure Python compatibility.
import os
import numpy as np
import pandas as pd
from matplotlib import pyplot
from scipy import optimize

# %matplotlib inline

"""Cargar dataset"""

# Solo tomar columnas 0,1,2 (como tu cuadernillo espera)
data = np.loadtxt('/content/drive/MyDrive/AtaquesR.csv',
                  delimiter=',',
                  usecols=(0,1,2))

X, y = data[:, 0:2], data[:, 2]

print(X)

"""Tamaño del dataset"""

print("Filas:", X.shape[0])
print("Columnas:", X.shape[1])

"""Visualizar datos"""

def plotData(X, y):

    fig = pyplot.figure()

    pos = y == 1
    neg = y == 0

    pyplot.plot(X[pos, 0], X[pos, 1], 'k*', lw=2, ms=10)
    pyplot.plot(X[neg, 0], X[neg, 1], 'ko', mfc='y', ms=8)

plotData(X, y)

pyplot.xlabel('Feature 1')
pyplot.ylabel('Feature 2')
pyplot.legend(['Ataque', 'Normal'])

"""Función Sigmoide"""

def calcularSigmoide(z):

    z = np.array(z)

    g = 1 / (1 + np.exp(-z))

    return g

"""Preparar matriz X"""

m, n = X.shape

X = np.concatenate([np.ones((m, 1)), X], axis=1)

print(X[:5])

"""Función de costo"""

def calcularCosto(theta, X, y):

    m = y.size

    h = calcularSigmoide(X.dot(theta.T))

    # evitar log(0)
    h = np.clip(h, 1e-10, 1 - 1e-10)

    J = (1 / m) * np.sum(-y.dot(np.log(h)) - (1 - y).dot(np.log(1 - h)))

    return J

"""Descenso por gradiente"""

def descensoGradiente(theta, X, y, alpha, num_iters):

    m = y.shape[0]

    theta = theta.copy()

    J_history = []

    for i in range(num_iters):

        h = calcularSigmoide(X.dot(theta.T))

        theta = theta - (alpha / m) * (h - y).dot(X)

        J_history.append(calcularCosto(theta, X, y))

    return theta, J_history

"""Entrenar modelo"""

alpha = 0.01
num_iters = 1000

theta = np.zeros(3)

theta, J_history = descensoGradiente(theta, X, y, alpha, num_iters)

"""Graficar convergencia"""

pyplot.plot(np.arange(len(J_history)), J_history)
pyplot.xlabel('Iteraciones')
pyplot.ylabel('Costo')

"""Resultado de theta"""

print("Theta encontrado:", theta)
print("Costo final:", J_history[-1])

"""Hacer predicciones"""

X_array = [1, 0.2, 0.5]

prob = calcularSigmoide(np.dot(X_array, theta))

print("Probabilidad de ataque:", prob)