# -*- coding: utf-8 -*-
"""CreditExa1.6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lu6Lk3m5Ww9ORMdgRV9z7j-orm-RVu5L

Credit Approval  

  Descripción:

Objetivo: Predecir si se aprueba un crédito bancario (clasificación binaria).  

Archivo recomendado: crx.data  

Variables clave:  

| Variable | Tipo | Descripción |
|----------|------|------------|
| 1-15 | mixto | Características del solicitante (edad, ingresos, deuda, historial) |
| class | categórico | Objetivo: + (aprobado) / - (rechazado) |
Filas y columnas: 690 filas, 16 columnas
Notas: contiene valores faltantes marcados con
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
sns.set(style="whitegrid")

# Cargar dataset
credit = pd.read_csv("/content/drive/MyDrive/crx.data", header=None, na_values='?')

# Asignar nombres genéricos
credit.columns = [f"V{i}" for i in range(1,17)]

# Primer vistazo
display(credit.head())
credit.info()
credit.describe()

# Revisar valores nulos
print("Valores nulos:")
print(credit.isnull().sum())

# Limpieza mínima: numéricos con media, categóricos con moda
for col in credit.columns:
    if credit[col].dtype == 'object':
        credit[col] = credit[col].fillna(credit[col].mode()[0])
    else:
        credit[col] = credit[col].fillna(credit[col].mean())

# Ejemplo gráfico: distribución de aprobación
sns.countplot(x='V16', data=credit)
plt.title("Distribución de aprobación de crédito")
plt.show()