# -*- coding: utf-8 -*-
"""HotelesP1/26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bunmmrmMea53Of5zOzT5ZRU-bmglrm-0

Demanda de reserva de hotel  
¿Te has preguntado alguna vez cuál es la mejor época del año para reservar una habitación de hotel? ¿O cuál es la duración óptima de la estancia para obtener la mejor tarifa diaria? ¿Y si quisieras predecir si un hotel tiene probabilidades de recibir un número desproporcionadamente alto de solicitudes especiales?

Este conjunto de datos contiene información de reservas para un hotel urbano y un hotel vacacional, e incluye datos como la fecha de la reserva, la duración de la estancia, el número de adultos, niños y/o bebés, y el número de plazas de aparcamiento disponibles, entre otros.
  
  El dataset original de Hotel Booking Demand tiene:

m = 119,390 filas

n = 32 columnas

Importar librerias
"""

# Commented out IPython magic to ensure Python compatibility.
import os
import numpy as np
import pandas as pd

from matplotlib import pyplot
from mpl_toolkits.mplot3d import Axes3D

# %matplotlib inline

"""Cargar dataset"""

data = pd.read_csv('/content/drive/MyDrive/hotelesP1.zip')

print(data.head())
print(data.shape)

"""Seleccionar variables para regresión"""

data_model = data[['adults',
                   'children',
                   'stays_in_weekend_nights',
                   'stays_in_week_nights',
                   'total_of_special_requests',
                   'adr']]

data_model = data_model.dropna()

"""Separar X y Y"""

X = data_model.iloc[:, :5].values
y = data_model.iloc[:, 5].values

m = y.size

print("Cantidad de filas:", m)
print("Cantidad de columnas:", X.shape[1])

"""Normalizar características"""

def featureNormalize(X):

    X_norm = X.copy()
    mu = np.zeros(X.shape[1])
    sigma = np.zeros(X.shape[1])

    mu = np.mean(X, axis=0)
    sigma = np.std(X, axis=0)

    X_norm = (X - mu) / sigma

    return X_norm, mu, sigma

X_norm, mu, sigma = featureNormalize(X)

print("Media:", mu)
print("Desviación estándar:", sigma)

"""Agregar columna de unos"""

X = np.concatenate([np.ones((m,1)), X_norm], axis=1)

"""Función de costo"""

def computeCostMulti(X, y, theta):

    m = y.shape[0]

    J = (1/(2*m)) * np.sum(np.square(np.dot(X, theta) - y))

    return J

"""Descenso por gradiente"""

def gradientDescentMulti(X, y, theta, alpha, num_iters):

    m = y.shape[0]

    theta = theta.copy()

    J_history = []

    for i in range(num_iters):

        theta = theta - (alpha/m) * (np.dot(X,theta)-y).dot(X)

        J_history.append(computeCostMulti(X,y,theta))

    return theta, J_history

"""Entrenar el modelo"""

alpha = 0.01
num_iters = 5000

theta = np.zeros(6)

theta, J_history = gradientDescentMulti(X,y,theta,alpha,num_iters)

print("Theta calculado:", theta)

"""Graficar convergencia"""

pyplot.plot(np.arange(len(J_history)), J_history, lw=2)
pyplot.xlabel('Numero de iteraciones')
pyplot.ylabel('Costo J')

"""Predicción"""

X_array = [1,2,1,1,3,1]

X_array[1:6] = (X_array[1:6] - mu) / sigma

price = np.dot(X_array,theta)

print("Precio promedio predicho ADR:", price)

"""Ecuación normal"""

X2 = data_model.iloc[:, :5].values
y2 = data_model.iloc[:, 5].values

m = y2.size

X2 = np.concatenate([np.ones((m,1)), X2], axis=1)

def normalEqn(X,y):

    theta = np.zeros(X.shape[1])

    theta = np.dot(np.dot(np.linalg.inv(np.dot(X.T,X)),X.T),y)

    return theta

theta = normalEqn(X2,y2)

print("Theta calculado por ecuacion normal:",theta)

X_array = [1,2,1,1,3,1]

price = np.dot(X_array,theta)

print("Precio estimado ADR:",price)