# -*- coding: utf-8 -*-
"""MeningitisExa1.9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_JNVIgu2KiHK2mgb3Hhr6fco-uQzeotA

Meningitis Dataset with Missing Values  

  Descripción:

Objetivo: Análisis de pacientes con meningitis, contiene missing values para practicar limpieza de datos.
Archivo  

 recomendado: meningitis.csv
Variables clave: variables demográficas y clínicas (edad, sexo, diagnóstico, laboratorio, etc.)  

Filas y columnas: depende de la versión, ~300-400 filas  

Uso típico: análisis clínico, limpieza de missing values, estadística descriptiva
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
sns.set(style="whitegrid")

# Cargar dataset
meningitis = pd.read_csv("/content/drive/MyDrive/MeningExa1.9.csv")

# Primer vistazo
display(meningitis.head())
meningitis.info()
meningitis.describe()

# Revisar valores nulos
print("Valores nulos por columna:")
print(meningitis.isnull().sum())

# Limpieza mínima:
# - numéricos → rellenar con media
# - categóricos → rellenar con moda
for col in meningitis.columns:
    if meningitis[col].dtype == 'object':
        meningitis[col] = meningitis[col].fillna(meningitis[col].mode()[0])
    else:
        meningitis[col] = meningitis[col].fillna(meningitis[col].mean())

# Ejemplo gráfico: distribución de pacientes por sexo
if 'sex' in meningitis.columns:
    sns.countplot(x='sex', data=meningitis)
    plt.title("Distribución por sexo - Meningitis")
    plt.show()

# Ejemplo gráfico 2: distribución de edades (si hay columna 'Age')

if 'Age' in meningitis.columns:
    plt.figure(figsize=(8,4))
    sns.histplot(meningitis['Age'], bins=20, kde=True)
    plt.title("Distribución de edades")
    plt.show()

#(clasificación binaria)
X = meningitis.drop(columns=['Outcome'], errors='ignore')
y = meningitis['Outcome'] if 'Outcome' in meningitis.columns else np.random.randint(0,2,len(meningitis))
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
nn_model = MLPClassifier(hidden_layer_sizes=(10,10), max_iter=500)
nn_model.fit(X_scaled, y)
print("Meningitis")