# -*- coding: utf-8 -*-
"""MimicIIIExa1.2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GhmHVSN9gW0OCquRX2h7dYgT9pfwQ7oN

MIMIC-III Clinical Database Demo  

Archivos recomendados a descargar:  

Pacientes.csv → información básica de pacientes (edad, sexo)
Admisiones.csv → información de hospitalizaciones (fecha, tipo de admisión)  
tomaremos en cuenta:  

ICUSTAYS.csv → información de estancias en UCI
Contenido clave ejemplo (PATIENTS.csv):  

| Variable | Tipo | Descripción |
|----------|------|------------|
| subject_id | numérico | ID del paciente |
| gender | categórico | Sexo del paciente |
| dob | fecha | Fecha de nacimiento |
| dod | fecha | Fecha de muerte (si aplica) |
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="whitegrid")

# Cargar datasets demo
patients = pd.read_csv("/content/drive/MyDrive/PATIENTSExa1.21.csv")
admissions = pd.read_csv("/content/drive/MyDrive/ADMISSIONSExa1.22.csv")
icustays = pd.read_csv("/content/drive/MyDrive/ICUSTAYSExa1.23.csv")

# Primer vistazo
print("Patients dataset:")
display(patients.head())

print("Admissions dataset:")
display(admissions.head())

print("ICU Stays dataset:")
display(icustays.head())

# Información general
patients.info()
admissions.info()
icustays.info()

# Revisar valores nulos
print("Valores nulos en Patients:")
print(patients.isnull().sum())

# Limpieza mínima: fechas nulas en 'dod' a 'NA'
patients['dod'] = patients['dod'].fillna('NA')

# Ejemplo: número de pacientes por género
gender_count = patients['gender'].value_counts()
print("\nNúmero de pacientes por género:")
print(gender_count)

# Gráfico simple
plt.figure(figsize=(6,4))
sns.countplot(x='gender', data=patients)
plt.title("Número de pacientes por género")
plt.show()