# -*- coding: utf-8 -*-
"""StatlogExa1.7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gc8aQIrEMmZ7N_Zjuy_FBgyCX6gzHTJv

Statlog (Australian Credit Approval)  

  Descripción:

Objetivo: Similar a Credit Approval, predecir aprobación de crédito
Archivo recomendado: australian.dat  

Variables clave: 14 características + clase objetivo (0=no, 1=si)
Filas y columnas: 690 filas, 15 columnas  

Notas: todas son numéricas, algunas discretas, algunas continuas
Uso típico: clasificación binaria, análisis crediticio.
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
sns.set(style="whitegrid")

# Cargar dataset
statlog = pd.read_csv("/content/drive/MyDrive/australian.dat", header=None, delim_whitespace=True)

# Asignar nombres genéricos
statlog.columns = [f"V{i}" for i in range(1,16)]

# Primer vistazo
display(statlog.head())
statlog.info()
statlog.describe()

# Revisar valores nulos
print("Valores nulos:")
print(statlog.isnull().sum())

# Limpieza mínima: rellenar NA con media (aunque normalmente no hay NA)
for col in statlog.columns:
    statlog[col] = statlog[col].fillna(statlog[col].mean())

# Ejemplo gráfico: distribución de clase objetivo
sns.countplot(x='V15', data=statlog)
plt.title("Distribución de aprobación de crédito - Statlog")
plt.show()