# -*- coding: utf-8 -*-
"""TabularP4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LaNvpFNFtER05RHNbeUupcnjDVjNvYoB

Tabular Playground Series - Feb 2022
  
  El dataset Tabular Playground Series Febrero 2022 es un conjunto de datos tabular utilizado para clasificación multiclase. Contiene aproximadamente 300,000 ejemplos y 286 características numéricas que representan histogramas derivados de mediciones de ADN. El objetivo es predecir la especie de bacteria correspondiente a cada muestra.

Importar Librerias
"""

# Commented out IPython magic to ensure Python compatibility.
import os
import numpy as np

from matplotlib import pyplot
from scipy import optimize
import pandas as pd

# %matplotlib inline

"""Cargar Dataset"""

# Cargar dataset
data = pd.read_csv('/content/drive/MyDrive/TabularP4.csv')

print(data.head())
print(data.shape)

"""Procesamiento"""

# Separar X e y
X = data.drop('target', axis=1).values
y = data['target'].values

# Convertir etiquetas a números
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

m, n = X.shape

print("Filas (m):", m)
print("Columnas (n):", n)

"""Normalizacion"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = scaler.fit_transform(X)

"""Funciones"""

def sigmoid(z):
    return 1.0 / (1.0 + np.exp(-z))

def lrCostFunction(theta, X, y, lambda_):
    m = y.size

    h = sigmoid(X.dot(theta.T))

    temp = theta.copy()
    temp[0] = 0

    J = (1 / m) * np.sum(-y.dot(np.log(h)) - (1 - y).dot(np.log(1 - h))) \
        + (lambda_ / (2 * m)) * np.sum(np.square(temp))

    grad = (1 / m) * (h - y).dot(X) + (lambda_ / m) * temp

    return J, grad

"""One vs All"""

def oneVsAll(X, y, num_labels, lambda_):
    m, n = X.shape

    all_theta = np.zeros((num_labels, n + 1))

    X = np.concatenate([np.ones((m, 1)), X], axis=1)

    for c in np.arange(num_labels):
        initial_theta = np.zeros(n + 1)

        options = {'maxiter': 50}

        res = optimize.minimize(
            lrCostFunction,
            initial_theta,
            (X, (y == c), lambda_),
            jac=True,
            method='CG',
            options=options
        )

        all_theta[c] = res.x

    return all_theta

"""Entrenamiento"""

num_labels = len(np.unique(y))
lambda_ = 0.1

all_theta = oneVsAll(X, y, num_labels, lambda_)

print(all_theta.shape)

"""Prediccion"""

def predictOneVsAll(all_theta, X):
    m = X.shape[0]

    X = np.concatenate([np.ones((m, 1)), X], axis=1)

    p = np.argmax(sigmoid(X.dot(all_theta.T)), axis=1)

    return p

"""Precision"""

pred = predictOneVsAll(all_theta, X)

accuracy = np.mean(pred == y) * 100

print('Precisión del modelo: {:.2f}%'.format(accuracy))